Added Notification So a User can See when an update is available
electron/update-electron-app pull request #75
Opened 2021-03-07 17:48 UTC by thereaper90917

Added a Notification for When Updates Are Available the logging is cool but from a users perspective it would be nice to see that a 

download has started especially if you have slow internet.

2021-03-10 19:40 UTC, malept requested changes

2021-03-18 14:28 UTC, thereaper90917 commented on index.js
> +      timeoutType: "10"
added. the requested parameters to make the process more dynamic you can now, choose the message you want to show. and how long the notification should be also, you can enable or disable the notification.
![12](https://user-images.githubusercontent.com/42868546/111642596-e3ebe100-8806-11eb-9ea6-3b5f793e6100.jpeg)

2021-06-14 20:16 UTC, Aivolt1 approved these changes

2021-06-15 09:48 UTC, realDragonium requested changes
Please change those things, thanks :slightly_smiling_face:

2021-06-15 09:48 UTC, realDragonium commented on index.d.ts
> +
Fix indents please

2021-06-15 09:48 UTC, realDragonium commented on index.js
> +
remove please

2021-06-15 09:48 UTC, realDragonium commented on index.js
> +
unnecessary

2021-06-15 09:48 UTC, realDragonium commented on index.js
> +  const { host, repo, updateInterval, logger, electron, userNotificationMessage, userNotificationTime} = opts
Missing a space before the `}`

2021-06-15 09:48 UTC, realDragonium commented on index.js
> +
unnecessary new line

2021-06-15 09:48 UTC, realDragonium commented on index.js
> +
unnecessary newline

2021-06-15 09:48 UTC, realDragonium commented on index.js
> +
unnecessary newlines

2021-06-15 09:52 UTC, thereaper90917 commented on index.d.ts
> +
fixed indents

2021-06-15 10:07 UTC, thereaper90917 commented on index.js
> +
fixed

2021-06-15 10:08 UTC, thereaper90917 commented on index.js
> +
fixed

2021-06-15 10:08 UTC, thereaper90917 commented on index.js
> +
removed

2021-06-15 10:09 UTC, thereaper90917 commented on index.js
> +
removed

2021-06-15 10:09 UTC, thereaper90917 commented on index.js
> +
removed

2021-06-15 10:09 UTC, thereaper90917 commented on index.js
> +  const { host, repo, updateInterval, logger, electron, userNotificationMessage, userNotificationTime} = opts
added

2021-06-15 10:10 UTC, realDragonium approved these changes
Looks a lot better now, thanks!

2021-07-01 21:48 UTC, DJRolls approved these changes
I love

2023-11-08 00:24 UTC, erickzhao requested changes
Hey @thereaper90917, thanks for the PR. I don't think notifying users on download is something we want to explicitly support since it can be disruptive to users.

Maybe an alternative would be to allow a callback for Electron apps to hook their own code once the download is started?

2023-11-08 00:24 UTC, closed without merging